/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01archivos;

import java.io.File;
import java.nio.file.DirectoryStream.Filter;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author criss
 */
public class FormAbrirArchivo extends javax.swing.JFrame {

    /**
     * Creates new form FormAbrirArchivo
     */
    public FormAbrirArchivo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionar.setText("Seleccionar");
        seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarMouseClicked(evt);
            }
        });
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(seleccionar)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionarMouseClicked
        // TODO add your handling code here:
        String temp = "";
        JFileChooser pdfruta = new JFileChooser();
        pdfruta.setDialogTitle("Seleccione la carpeta");
        pdfruta.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if(pdfruta.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File archivo = pdfruta.getSelectedFile();
            if(archivo.isDirectory())
            {
                lectorCarpetas(archivo);
            }
            else if (archivo.isFile())
            {
                lectorArchivosPDF(archivo);
            }
        }
    }//GEN-LAST:event_seleccionarMouseClicked

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbrirArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAbrirArchivo().setVisible(true);
            }
        });
    }
    
    private void lectorCarpetas(File archivo)
    {
        String temp = "";
        for (final File fileEntry : archivo.listFiles()) 
            {
             if (fileEntry.isDirectory()) {
            System.out.println("leyendo archivos de la caarpeta " + archivo.getAbsolutePath());
            lectorCarpetas(fileEntry);
              } else {
                if (fileEntry.isFile()) {
                temp = fileEntry.getName();
                 if ((temp.substring(temp.lastIndexOf('.') + 1, temp.length()).toLowerCase()).equals("pdf"))
                 {
                     System.out.println("----------------------------------");
                     System.out.println("Leyendo el pdf: " + fileEntry.getName());
                     String aux = archivo.getAbsolutePath()+ "\\" + fileEntry.getName();
                     File archivopdf = new File(aux);
                     lectorArchivosPDF(archivopdf);
                 }
                }

                }
           }
    }
     
    private void lectorArchivosPDF(File archivo)
    {
        LectorPDF lector = new LectorPDF(archivo);
          int a = lector.LecturaMetaDatos().split("/").length;
          String[] partir = lector.LecturaMetaDatos().split("/");
          System.out.println("Los metadatos son:");
           for(int j=1; j<a; j++)
          {
           System.out.println(partir[j]);
          }
    
          System.out.println("La version del PDF es: " + lector.LecturaVersion());
          System.out.println(lector.Tamanio());
          System.out.println("Número de Páginas: "+lector.Numpaginas());
          System.out.println("Tamaño de Página: "+ lector.TamanioPag()+ " mm");
          System.out.println("Listado de Imágenes: "+ lector.LectorImagenes());
          System.out.println("Listado de Fuentes: " + lector.LectordeFuentes());
          System.out.println();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
